version: '3'
services:
    app:
        container_name: info-scraper
        image: infoscraper:1.0.0
        ports:
            - "3000:3000"
        environment:
            - APP_PORT=3000
            - DATABASE_PORT=5432
            - DATABASE_HOST=192.168.0.19
            - DATABASE_NAME=info_scraper
            - DATABASE_USERNAME=postgres
            - DATABASE_PASSWORD=postgres
        networks:
            - localdb

networks:
    localdb:
