
http://localhost:3000/infoscraper/stocks/v1/list

###

http://localhost:3000/infoscraper/stocks/v1/ticker/123

###

http://localhost:3000/infoscraper/stocks/v1/highs/

###

http://localhost:3000/infoscraper/stocks/v1/all?page=1

###

http://localhost:3000/infoscraper/stocks/v1/downs/